package tokoalatkesehatan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.SQLIntegrityConstraintViolationException;

/**
 *
 * @author ADELIA
 */

public class FormSignUp extends javax.swing.JFrame {
    Connection conn = null;
    Statement st = null;

    public FormSignUp(java.awt.Frame parent, boolean modal) {
        initComponents();
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/alat_kesehatan","root","");
            st = conn.createStatement();
            System.out.println("Berhasil Koneksi");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Gagal Terhubung Ke Koneksi, karena "+ex);
        }
    }
    
    private void hapusLayar(){
        txtUser.setText("");
        txtPass.setText("");
        txtKPassword.setText("");
        txtEmail.setText("");
        txtttl.setText("");
        txtAlamat.setText("");
        txtNoTelp.setText("");
        txtPayPal.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jSlider1 = new javax.swing.JSlider();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        canvas1 = new java.awt.Canvas();
        signup = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        kPassword = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        btnSignUp = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        SIGNUP = new javax.swing.JLabel();
        txtKPassword = new javax.swing.JPasswordField();
        txtttl = new javax.swing.JTextField();
        email = new javax.swing.JLabel();
        tanggalLahir = new javax.swing.JLabel();
        gender = new javax.swing.JLabel();
        btnLaki = new javax.swing.JRadioButton();
        btnPerempuan = new javax.swing.JRadioButton();
        notelp = new javax.swing.JLabel();
        paypal = new javax.swing.JLabel();
        txtPayPal = new javax.swing.JPasswordField();
        alamat = new javax.swing.JLabel();
        kPassword1 = new javax.swing.JLabel();
        txtNoTelp = new javax.swing.JTextField();
        kota = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        username.setText("Username ");

        password.setText("Password ");

        kPassword.setText("Ketik Password");

        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });

        btnSignUp.setBackground(new java.awt.Color(204, 204, 204));
        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(204, 204, 204));
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        SIGNUP.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SIGNUP.setText("FORM REGISTRASI");

        txtKPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKPasswordActionPerformed(evt);
            }
        });

        txtttl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtttlActionPerformed(evt);
            }
        });

        email.setText("E-mail");

        tanggalLahir.setText("Tanggal Lahir");

        gender.setText("Gender");

        btnLaki.setText("Laki-Laki");
        btnLaki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLakiActionPerformed(evt);
            }
        });

        btnPerempuan.setText("Perempuan");

        notelp.setText("No Telp");

        paypal.setText("Pay-pal ID");

        txtPayPal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPayPalActionPerformed(evt);
            }
        });

        alamat.setText("Alamat");

        kPassword1.setText("Kota");

        txtNoTelp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoTelpActionPerformed(evt);
            }
        });

        kota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        kota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kotaActionPerformed(evt);
            }
        });

        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout signupLayout = new javax.swing.GroupLayout(signup);
        signup.setLayout(signupLayout);
        signupLayout.setHorizontalGroup(
            signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(signupLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnSignUp)
                                .addGap(83, 83, 83)
                                .addComponent(btnBack))
                            .addGroup(signupLayout.createSequentialGroup()
                                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(username)
                                    .addComponent(password)
                                    .addComponent(kPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tanggalLahir)
                                    .addComponent(email))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtttl, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtUser)
                                        .addComponent(txtPass)
                                        .addComponent(txtKPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(signupLayout.createSequentialGroup()
                                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(notelp)
                                    .addComponent(paypal)
                                    .addComponent(alamat))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(signupLayout.createSequentialGroup()
                                        .addComponent(btnLaki)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnPerempuan))
                                    .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(38, 38, 38))))
            .addGroup(signupLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(SIGNUP)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        signupLayout.setVerticalGroup(
            signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signupLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(SIGNUP)
                .addGap(33, 33, 33)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(username)
                            .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addComponent(password)
                        .addGap(18, 18, 18)
                        .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(email)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLaki)
                            .addComponent(btnPerempuan)))
                    .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tanggalLahir)
                        .addComponent(txtttl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(alamat))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(12, 12, 12)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addComponent(notelp))
                    .addGroup(signupLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(txtNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPayPal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(paypal))
                .addGap(40, 40, 40)
                .addGroup(signupLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSignUp)
                    .addComponent(btnBack))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signup, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPassActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        try {
    // Validasi input
    if (txtUser.getText().isEmpty() || String.valueOf(txtPass.getPassword()).isEmpty() || 
            String.valueOf(txtKPassword.getPassword()).isEmpty() || txtttl.getText().isEmpty() ||
            txtAlamat.getText().isEmpty() || txtNoTelp.getText().isEmpty() || txtPayPal.getText().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Pesan", JOptionPane.ERROR_MESSAGE);
        hapusLayar();
    } else {
        String jenisKelamin = (btnLaki.isSelected()) ? "Laki-Laki" : "Perempuan";
        String kotaUser = kota.getSelectedItem().toString();

        // Query SQL dengan parameter untuk menghindari SQL injection
        String simpan = "INSERT INTO USER (USERNAME_USER, PASSWORD_USER, EMAIL_USER, TANGGAL_LAHIR_USER, JK_USER, ALAMAT_USER, KOTA_USER, NO_TELP_USER, PAYPAL_ID_USER) VALUES "
                + "(?, ?, ?, ?, ?, ?, ?, ?, ?)";

        // Gunakan PreparedStatement untuk mencegah SQL injection
        PreparedStatement preparedStatement = conn.prepareStatement(simpan);
        preparedStatement.setString(1, txtUser.getText());
        preparedStatement.setString(2, String.valueOf(txtPass.getPassword()));
        preparedStatement.setString(3, txtEmail.getText());
        preparedStatement.setString(4, txtttl.getText());
        preparedStatement.setString(5, jenisKelamin);
        preparedStatement.setString(6, txtAlamat.getText());
        preparedStatement.setString(7, kotaUser);
        preparedStatement.setString(8, txtNoTelp.getText());
        preparedStatement.setString(9, txtPayPal.getText());

        // Lakukan eksekusi SQL
        preparedStatement.executeUpdate();

        JOptionPane.showMessageDialog(this, "Sign Up Berhasil");
        this.setVisible(false);
        new FormLogIn(null, true).setVisible(true);
    }
}catch (SQLException e) {
    if (e instanceof SQLIntegrityConstraintViolationException) {
        JOptionPane.showMessageDialog(this, "Username atau Email sudah digunakan",
                "Pesan", JOptionPane.WARNING_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(),
                "Pesan", JOptionPane.ERROR_MESSAGE);
    }
    hapusLayar();
}

    }//GEN-LAST:event_btnSignUpActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new FormLogIn(null,true).setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtKPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKPasswordActionPerformed

    private void txtttlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtttlActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtttlActionPerformed

    private void btnLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLakiActionPerformed

    private void txtPayPalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPayPalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPayPalActionPerformed

    private void txtNoTelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoTelpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoTelpActionPerformed

    private void kotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kotaActionPerformed
        // TODO add your handling code here:
        kota.removeAllItems();
        kota.addItem("Kota Surabaya");
        kota.addItem("Kota Jakarta");
        kota.addItem("Kota Bali");
    }//GEN-LAST:event_kotaActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new FormSignUp(null,true).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SIGNUP;
    private javax.swing.JLabel alamat;
    private javax.swing.JButton btnBack;
    private javax.swing.JRadioButton btnLaki;
    private javax.swing.JRadioButton btnPerempuan;
    private javax.swing.JButton btnSignUp;
    private java.awt.Canvas canvas1;
    private javax.swing.JLabel email;
    private javax.swing.JLabel gender;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JSlider jSlider1;
    private javax.swing.JLabel kPassword;
    private javax.swing.JLabel kPassword1;
    private javax.swing.JComboBox<String> kota;
    private javax.swing.JLabel notelp;
    private javax.swing.JLabel password;
    private javax.swing.JLabel paypal;
    private javax.swing.JPanel signup;
    private javax.swing.JLabel tanggalLahir;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtKPassword;
    private javax.swing.JTextField txtNoTelp;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JPasswordField txtPayPal;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtttl;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
