/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tokoalatkesehatan;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.sql.Timestamp;
import java.util.logging.Logger;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;




/**
 *
 * @author Windows 10
 */
public class Keranjang extends javax.swing.JFrame {

    /**
     * Creates new form Keranjang
     */
    Connection conn = null;
    PreparedStatement stmt = null;
    Statement st = null;
    ResultSet rs = null;
    private int idUser;
    public Keranjang(int idUserInput) {
        initComponents();
        this.idUser=idUserInput;
        try{
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost/alat_kesehatan","root","");
            st = conn.createStatement();
            System.out.println("Berhasil Terkoneksi Database");
        }catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Gagal Terhubung Ke Koneksi, karena "+ex);
        }
        select();
//        showPelanggan();
        System.out.println(idUser);
    }
    
    //menampilkan
    public void select(){
        try {
        // Mengatur query untuk mengambil data barang
        String query = "SELECT id_barang, kode_barang, nama_barang, harga_barang, stok_barang FROM manajemen";
        stmt = conn.prepareStatement(query);
        
        // Mengeksekusi query dan mendapatkan hasilnya
        rs = stmt.executeQuery();
        
        // Mengatur model tabel
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Id Barang");
        model.addColumn("Kode");
        model.addColumn("Nama Barang");
        model.addColumn("Harga");
        model.addColumn("Stok");
        
        // Menambahkan data barang ke dalam model
        while (rs.next()) {
            String id_barang = rs.getString("id_barang");
            String kode = rs.getString("kode_barang");
            String namaBarang = rs.getString("nama_barang");
            String harga = rs.getString("harga_barang");
            String stok = rs.getString("stok_barang");
            
            model.addRow(new Object[] {id_barang, kode, namaBarang, harga, stok});
        }
        
        // Mengatur model tabel pada tabelCari
        tableCari.setModel(model);
    } catch (SQLException e) {
        e.printStackTrace();
    }
    }
    
    
    public void setTotalHarga(){
        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
        // Menghitung total harga
        double totalHarga = 0;
        for (int row = 0; row < model.getRowCount(); row++) {
            double total = Double.parseDouble(model.getValueAt(row, 5).toString());
            totalHarga += total;
        }

        // Menampilkan total harga di bidang teks
        totalHargaTextField.setText(String.valueOf(totalHarga));
    }
    
    //
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPencarian = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        buttonPelanggan = new javax.swing.JButton();
        buttonManajemenBarang = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buttonHapus = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        barangKode = new javax.swing.JTextField();
        buttonTambah = new javax.swing.JButton();
        barangNama = new javax.swing.JTextField();
        barangHarga = new javax.swing.JTextField();
        barangJumlah = new javax.swing.JTextField();
        barangTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buttonEdit = new javax.swing.JButton();
        barangId = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        judul = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCari = new javax.swing.JTable();
        totalHargaTextField = new javax.swing.JTextField();
        buttonBayar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("PRODUCT PAGE");

        buttonPelanggan.setText("Pelanggan");
        buttonPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPelangganActionPerformed(evt);
            }
        });

        buttonManajemenBarang.setText("Manajemen Barang");
        buttonManajemenBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonManajemenBarangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPencarianLayout = new javax.swing.GroupLayout(panelPencarian);
        panelPencarian.setLayout(panelPencarianLayout);
        panelPencarianLayout.setHorizontalGroup(
            panelPencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPencarianLayout.createSequentialGroup()
                .addComponent(buttonPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104)
                .addComponent(jLabel4)
                .addGap(116, 116, 116)
                .addComponent(buttonManajemenBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPencarianLayout.setVerticalGroup(
            panelPencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPencarianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPencarianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonPelanggan)
                    .addComponent(buttonManajemenBarang)
                    .addComponent(jLabel4))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jLabel2.setText("Jumlah");

        buttonHapus.setText("Hapus");
        buttonHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonHapusActionPerformed(evt);
            }
        });

        jLabel3.setText("Total");

        barangKode.setEditable(false);

        buttonTambah.setText("Tambah");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        barangNama.setEditable(false);

        barangHarga.setEditable(false);

        barangJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                barangJumlahKeyReleased(evt);
            }
        });

        barangTotal.setEditable(false);

        jLabel1.setText("Kode");

        buttonEdit.setText("Edit");
        buttonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEditActionPerformed(evt);
            }
        });

        barangId.setEditable(false);
        barangId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barangIdActionPerformed(evt);
            }
        });

        jLabel8.setText("ID");

        jLabel9.setText("Nama Barang");

        jLabel10.setText("Harga");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel1)
                                .addGap(45, 45, 45))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(barangId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(barangKode, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(barangNama, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(81, 81, 81)
                                .addComponent(jLabel2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(barangHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(barangJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barangTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barangNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barangKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barangHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barangJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barangTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barangId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonHapus)
                    .addComponent(buttonEdit)
                    .addComponent(buttonTambah)))
        );

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Barang", "Kode", "Nama Barang", "Harga", "Jumlah", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableTransaksi);

        judul.setText("Keranjang");

        jButton1.setText("Keluar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(judul)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 633, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(judul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        tableCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Barang", "Kode", "Nama Barang", "Harga", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCariMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableCari);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 909, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
        );

        totalHargaTextField.setEditable(false);
        totalHargaTextField.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        totalHargaTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalHargaTextFieldActionPerformed(evt);
            }
        });

        buttonBayar.setText("Bayar");
        buttonBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBayarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(totalHargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(181, 181, 181)
                                        .addComponent(buttonBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(totalHargaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
            // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();

        String kodeBarang = barangKode.getText();

    // Periksa apakah kode barang sudah ada dalam tabel
        for (int row = 0; row < tableTransaksi.getRowCount(); row++) {
            String kode = tableTransaksi.getValueAt(row, 1).toString();
            if (kode.equals(kodeBarang)) {
                JOptionPane.showMessageDialog(this, "Barang sudah ada dalam daftar transaksi.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
        }
        
        String id = barangId.getText();
        String kode = barangKode.getText();
        String nama = barangNama.getText();
        String harga = barangHarga.getText();
        String jumlah = barangJumlah.getText();
        String total = barangTotal.getText();
        if (id.isEmpty()||kode.isEmpty() || nama.isEmpty() || harga.isEmpty() || jumlah.isEmpty() || total.isEmpty() ) {
            buttonTambah.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Lengkapi semua field terlebih dahulu", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        int selectedRow = tableCari.getSelectedRow();
        int barangJumlahInt = Integer.parseInt(jumlah);
        int tableCariJumlah = Integer.parseInt(tableCari.getValueAt(selectedRow, 4).toString());
        if(barangJumlahInt > tableCariJumlah ){
            JOptionPane.showMessageDialog(this, "Stok Barang Tinggal "+tableCariJumlah +".", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        

        Object[] rowData = {id,kode, nama, harga, jumlah, total};
        model.addRow(rowData);

        tableTransaksi.setModel(model);
        barangId.setText("");
        barangKode.setText("");
        barangNama.setText("");
        barangHarga.setText("");
        barangJumlah.setText("");
        barangTotal.setText("");
        setTotalHarga();
        tableCari.clearSelection();
        tableTransaksi.clearSelection();
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonHapusActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableTransaksi.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        String id = tableTransaksi.getValueAt(selectedRow, 0).toString();
        String kode = tableTransaksi.getValueAt(selectedRow, 1).toString();
        String nama = tableTransaksi.getValueAt(selectedRow, 2).toString();
        String harga = tableTransaksi.getValueAt(selectedRow, 3).toString();
        String jumlah = tableTransaksi.getValueAt(selectedRow, 4).toString();
        String total = tableTransaksi.getValueAt(selectedRow, 5).toString();

        barangId.setText(id);
        barangKode.setText(kode);
        barangNama.setText(nama);
        barangHarga.setText(harga);
        barangJumlah.setText(jumlah);
        barangTotal.setText(total);

        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
        model.removeRow(selectedRow);
        barangId.setText("");
        barangKode.setText("");
        barangNama.setText("");
        barangHarga.setText("");
        barangJumlah.setText("");
        barangTotal.setText("");
        setTotalHarga();
        tableTransaksi.clearSelection();
    }//GEN-LAST:event_buttonHapusActionPerformed

    private void tableCariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCariMouseClicked
        // TODO add your handling code here:
        int row = tableCari.getSelectedRow();
        barangId.setText(tableCari.getValueAt(row, 0).toString());
        barangKode.setText(tableCari.getValueAt(row, 1).toString());
        barangNama.setText(tableCari.getValueAt(row, 2).toString());
        barangHarga.setText(tableCari.getValueAt(row, 3).toString());
        barangJumlah.setText("0");
        barangTotal.setText("0");
        buttonTambah.setEnabled(true);
        buttonEdit.setEnabled(false);
        buttonHapus.setEnabled(false);
    }//GEN-LAST:event_tableCariMouseClicked

    private void barangJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_barangJumlahKeyReleased
        // TODO add your handling code here:
        String jumlahString = barangJumlah.getText();
        
        // Mengubah string menjadi integer
        int jumlah = 0;
        if (!jumlahString.isEmpty()) {
            jumlah = Integer.parseInt(jumlahString);
        }
        
        // Mendapatkan nilai dari field barangHarga
        String hargaString = barangHarga.getText();
        
        // Mengubah string menjadi integer
        float harga = 0;
        if (!hargaString.isEmpty()) {
            harga = Float.parseFloat(hargaString);
        }
        
        // Menghitung total
        float total = harga * jumlah;
        
        // Menampilkan hasil di field barangTotal
        barangTotal.setText(Float.toString(total));
    }//GEN-LAST:event_barangJumlahKeyReleased

    private void buttonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEditActionPerformed
        // TODO add your handling code here:
         int selectedRow = tableTransaksi.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diedit.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Ambil nilai dari baris yang dipilih
        String idBarang = barangId.getText();
        String kodeBarang = barangKode.getText();
        String namaBarang = barangNama.getText();
        String hargaBarang = barangHarga.getText();
        String jumlahBarang = barangJumlah.getText();
        String totalBarang = barangTotal.getText();
        if (idBarang.isEmpty() || kodeBarang.isEmpty() || namaBarang.isEmpty() || hargaBarang.isEmpty() || jumlahBarang.isEmpty() || totalBarang.isEmpty()) {
            buttonTambah.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Pilih Barang di Transaksi dulu!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (int row = 0; row < tableCari.getRowCount(); row++) {
            String id = tableCari.getValueAt(row, 0).toString();
            if (id.equals(idBarang)) {
                int barangJumlahInt = Integer.parseInt(jumlahBarang);
                int tableCariJumlah = Integer.parseInt(tableCari.getValueAt(row, 4).toString());
                if(barangJumlahInt > tableCariJumlah ){
                    JOptionPane.showMessageDialog(this, "Stok Barang Tinggal "+tableCariJumlah +".", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }
        }
        
        
        
        tableTransaksi.setValueAt(idBarang, selectedRow, 0);
        tableTransaksi.setValueAt(kodeBarang, selectedRow, 1);
        tableTransaksi.setValueAt(namaBarang, selectedRow, 2);
        tableTransaksi.setValueAt(hargaBarang, selectedRow, 3);
        tableTransaksi.setValueAt(jumlahBarang, selectedRow, 4);
        tableTransaksi.setValueAt(totalBarang, selectedRow, 5);

        // Reset field input
        barangId.setText("");
        barangKode.setText("");
        barangNama.setText("");
        barangHarga.setText("");
        barangJumlah.setText("");
        barangTotal.setText("");
        tableTransaksi.clearSelection();
        setTotalHarga();
    }//GEN-LAST:event_buttonEditActionPerformed

    private void tableTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableTransaksiMouseClicked
        // TODO add your handling code here:
        int row = tableTransaksi.getSelectedRow();
        barangId.setText(tableTransaksi.getValueAt(row, 0).toString());
        barangKode.setText(tableTransaksi.getValueAt(row, 1).toString());
        barangNama.setText(tableTransaksi.getValueAt(row, 2).toString());
        barangHarga.setText(tableTransaksi.getValueAt(row, 3).toString());
        barangJumlah.setText(tableTransaksi.getValueAt(row, 4).toString());
        barangTotal.setText(tableTransaksi.getValueAt(row, 5).toString());
        buttonTambah.setEnabled(false);
        buttonEdit.setEnabled(true);
        buttonHapus.setEnabled(true);
       
    }//GEN-LAST:event_tableTransaksiMouseClicked

    private void buttonBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBayarActionPerformed
                                        
    LocalDateTime currentDateTime = LocalDateTime.now();
    Timestamp timestamp = Timestamp.valueOf(currentDateTime);
    
    int idTransaksi = 0;

    String query = "INSERT INTO transaksi (id_pelanggan, id_user, TANGGAL_TRANSAKSI) VALUES (?, ?, ?)";

    try {
        PreparedStatement statementTransaksi = conn.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);

        // ID pelanggan diabaikan (NULL) dalam query
        statementTransaksi.setNull(1, java.sql.Types.INTEGER);
        
        statementTransaksi.setInt(2, this.idUser);
        statementTransaksi.setTimestamp(3, timestamp);

        int rowsInsertedTransaksi = statementTransaksi.executeUpdate();

        if (rowsInsertedTransaksi > 0) {
            ResultSet generatedKeys = statementTransaksi.getGeneratedKeys();
            if (generatedKeys.next()) {
                idTransaksi = generatedKeys.getInt(1);
                System.out.println("ID Transaksi baru: " + idTransaksi);
            }
        } else {
            System.out.println("Gagal insert transaksi.");
        }
    } catch (SQLException ex) {
        System.out.println("Gagal insert. Pesan kesalahan: " + ex.getMessage());
    }
    



    }//GEN-LAST:event_buttonBayarActionPerformed

    private void buttonPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPelangganActionPerformed
        this.setVisible(false);
        new framePelanggan().setVisible(true);
    }//GEN-LAST:event_buttonPelangganActionPerformed

    private void buttonManajemenBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonManajemenBarangActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new JFrame_barang().setVisible(true);
    }//GEN-LAST:event_buttonManajemenBarangActionPerformed

    private void barangIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barangIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barangIdActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void totalHargaTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalHargaTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalHargaTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keranjang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                String idUser = args[0]; // Get the idUser from command line arguments
//                new Penjualan(idUser).setVisible(true);
//            }
//        });
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                String idUser = args[0]; // Get the idUser from command line arguments
//                new Keranjang(idUser).setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barangHarga;
    private javax.swing.JTextField barangId;
    private javax.swing.JTextField barangJumlah;
    private javax.swing.JTextField barangKode;
    private javax.swing.JTextField barangNama;
    private javax.swing.JTextField barangTotal;
    private javax.swing.JButton buttonBayar;
    private javax.swing.JButton buttonEdit;
    private javax.swing.JButton buttonHapus;
    private javax.swing.JButton buttonManajemenBarang;
    private javax.swing.JButton buttonPelanggan;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel judul;
    private javax.swing.JPanel panelPencarian;
    private javax.swing.JTable tableCari;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JTextField totalHargaTextField;
    // End of variables declaration//GEN-END:variables
}
